trigger:
- pr
    
pool:
  vmImage: 'vs2017-win2016'

variables:
  status: 'fail'

steps:
- checkout: self
  persistCredentials: "true"

- powershell: (new-object System.Net.WebClient).DownloadFile('http://www.nespowerpak.com/nesasm/NESASM3.zip','NESASM3.zip')
  displayName: 'Download NESASM3 for Windows'
  condition: not(contains(variables['Build.SourceVersionMessage'], '[skip ci]'))

- task: ExtractFiles@1
  displayName: 'Extract files'
  inputs:
    archiveFilePatterns: NESASM3.zip
    destinationFolder: NESASM3
  condition: not(contains(variables['Build.SourceVersionMessage'], '[skip ci]'))

- task: CmdLine@2
  displayName: 'Assemble source file (.NES ROM)'
  inputs:
    script: 'D:\a\1\s\NESASM3\NESASM3.exe D:\a\1\s\w2.asm'
  condition: not(contains(variables['Build.SourceVersionMessage'], '[skip ci]'))

- task: Bash@3
  displayName: 'Check assembly status'
  inputs:
    targetType: 'inline'
    script: |
      result=$(D:/a/1/s/NESASM3/NESASM3.exe D:/a/1/s/w2.asm | grep error)
      echo $result
      echo "##vso[task.setvariable variable=status]$result"
  condition: not(contains(variables['Build.SourceVersionMessage'], '[skip ci]'))
      
- task: Bash@3
  displayName: 'Fail build only if assembly fails'
  inputs:
    targetType: 'inline'
    script: exit 1
  condition: contains(variables['status'], 'error')
