
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: 'nesasm'
    type: 'github'
    name: 'camsaul/nesasm'
    endpoint: 'hxlnt'

steps:
- task: Bash@3
  displayName: Get NES assembler source
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/camsaul/nesasm.git'
      
- task: Bash@3
  displayName: 'Install NES assembler'
  inputs:
    targetType: 'inline'
    script: 'cd nesasm/source && make && sudo make install'

- task: Bash@3
  displayName: 'Assemble source file (.NES ROM)'
  inputs:
    targetType: 'inline'
    script: |
      'nesasm/nesasm w2.asm > cat assembly-status.txt'
      'status=`tail -1 assembly-status.txt`'
      'echo $status'
      'echo variables['status']'
    failOnStderr: true

- task: Bash@3
  displayName: 'Check for successful assembly'
  condition: and(always(), eq(status, 'pass 2'))