
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: 'nesasm'
    type: 'github'
    name: 'camsaul/nesasm'
    endpoint: 'hxlnt'

variables:
  status: 'fail'

steps:
- task: Bash@3
  displayName: Get NES assembler source
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/camsaul/nesasm.git'
      
- task: Bash@3
  displayName: 'Install NES assembler'
  inputs:
    targetType: 'inline'
    script: 'cd nesasm/source && make && sudo make install'

- task: Bash@3
  displayName: 'Assemble source file (.NES ROM)'
  inputs:
    targetType: 'inline'
    script: 'nesasm/nesasm w2.asm'
    failOnStderr: true

- task: Bash@3
  displayName: 'Check assembly status'
  inputs:
    targetType: 'inline'
    script: |
      result=$(nesasm/nesasm w2.asm | grep error)
      echo $result
      echo "##vso[task.setvariable variable=status]$result"
      
- task: Bash@3
  displayName: 'Fail build only if assembly fails'
  inputs:
    targetType: 'inline'
    script: exit 1
  condition: contains(variables['status'], 'error')

- task: Bash@3
  displayName: 'Install emulator'
  inputs:
    targetType: 'inline'
    script: 'sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && sudo apt install apt-transport-https ca-certificates && echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list && sudo apt update'

- task: Bash@3
  displayName: 'Install emulator dependencies'
  inputs:
    targetType: 'inline'
    script: sudo apt-get update && sudo apt-get install -y gnome-themes-standard libsdl2-2.0 mono-complete && curl -sL Mesen.0.9.7.zip

- task: Bash@3
  displayName: 'Install emulator'
  inputs:
    targetType: 'inline'
    script: 'unzip Mesen.0.9.7.zip'

- task: Bash@3
  displayName: 'Run emulator'
  inputs:
    targetType: 'inline'
    script: 'mono Mesen.exe w2.nes'

- task: Bash@3
  displayName: 'Install screenshot tool'
  inputs:
    targetType: 'inline'
    script: 'pip3 install screenshot'

- task: Bash@3
  displayName: 'Take screenshot after 1 second'
  inputs:
    targetType: 'inline'
    script: 'screenshot OpenEmu --filename "build/screenshot.png"'
