# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2
  inputs:
    script: 'mkdir nesasm && git clone https://github.com/camsaul/nesasm.git'
    failOnStderr: true
  displayName: 'Clone nesasm3'

- task: CmdLine@2
  inputs:
    script: 'cd source && make && sudo make install'
    failOnStderr: true
  displayName: 'Install nesasm3'

# Copy Files
# Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
- task: CopyFiles@2
  inputs:
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
    overWrite: true

- script: |
    nesasm3 w2.asm
  displayName: 'Run nesasm3'

