
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: 'nesasm'
    type: 'github'
    name: 'camsaul/nesasm'
    endpoint: 'hxlnt'

# variables:
#   status: fail

steps:
- task: Bash@3
  displayName: Get NES assembler source
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/camsaul/nesasm.git'
      
- task: Bash@3
  displayName: 'Install NES assembler'
  inputs:
    targetType: 'inline'
    script: 'cd nesasm/source && make && sudo make install'

- task: Bash@3
  displayName: 'Assemble source file (.NES ROM)'
  inputs:
    targetType: 'inline'
    script: 'nesasm/nesasm w2.asm'
    failOnStderr: true

- task: Bash@3
  displayName: 'Check assembly status'
  inputs:
    status: $(status)
    targetType: 'inline'
    script: |
      # 'status=`nesasm/nesasm w2.asm | grep "pass 2"`
      echo '##vso[task.setvariable variable=status]`nesasm/nesasm w2.asm | grep "pass 2"`'

- task: Bash@3
  displayName: 'Check for successful assembly'
  inputs:
    failOnStderr: true
    script: exit 1
  condition: ne($(status), 'pass 2')