# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'git checkout https://github.com/camsaul/nesasm.git
      
      # Use the environment variables input below to pass secret variables to this script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cd nesasm/source && make && sudo make install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'nesasm3'