
trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

resources:
  repositories:
  - repository: 'nesasm'
    type: 'github'
    name: 'camsaul/nesasm'
    endpoint: 'hxlnt'

variables:
  status: 'fail'

steps:

# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.6'
#     architecture: 'x64'

- powershell: (new-object System.Net.WebClient).DownloadFile('http://www.nespowerpak.com/nesasm/NESASM3.zip','NESASM3.zip')
  displayName: 'Download NESASM3 for Windows'

- task: ExtractFiles@1
  displayName: 'Extract files'
  inputs:
    archiveFilePatterns: NESASM3.zip
    destinationFolder: build

- task: Bash@3
  displayName: 'Assemble source file (.NES ROM)'
  inputs:
    targetType: 'inline'
    script: 'ls && build/nesasm3/nesasm3.exe -lua build/screenshot.lua w2.asm && sleep 1 && ls'
    failOnStderr: true

- task: Bash@3
  displayName: 'Check assembly status'
  inputs:
    targetType: 'inline'
    script: |
      result=$(nesasm3/nesasm3 w2.asm | grep error)
      echo $result
      echo "##vso[task.setvariable variable=status]$result"
      
- task: Bash@3
  displayName: 'Fail build only if assembly fails'
  inputs:
    targetType: 'inline'
    script: exit 1
  condition: contains(variables['status'], 'error')
