
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: 'nesasm'
    type: 'github'
    name: 'camsaul/nesasm'
    endpoint: 'hxlnt'

variables:
  status: 'fail'

steps:
- task: Bash@3
  displayName: Get NES assembler source
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/camsaul/nesasm.git'
      
- task: Bash@3
  displayName: 'Install NES assembler'
  inputs:
    targetType: 'inline'
    script: 'cd nesasm/source && make && sudo make install'

- task: Bash@3
  displayName: 'Assemble source file (.NES ROM)'
  inputs:
    targetType: 'inline'
    script: 'nesasm/nesasm w2.asm'
    failOnStderr: true

- task: Bash@3
  displayName: 'Check assembly status'
  inputs:
    targetType: 'inline'
    script: |
      result=$(nesasm/nesasm w2.asm | grep error)
      echo $result
      echo "##vso[task.setvariable variable=status]$result"
      
- task: Bash@3
  displayName: 'Fail build only if assembly fails'
  inputs:
    targetType: 'inline'
    script: exit 1
  condition: contains(variables['status'], 'error')

- task: Bash@3
  displayName: 'Install emulator'
  inputs:
    targetType: 'inline'
    script: |
      sudo rm -f /etc/apt/sources.list.d/sdlmame4ubuntu.*
      sudo add-apt-repository ppa:c.falco/mame
      sudo apt-get update
      sudo apt-get install mame
      mame w2.nes -str 6
