# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: 'nesasm'
    type: 'github'
    name: 'camsaul/nesasm'
    endpoint: 'hxlnt'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/camsaul/nesasm.git'
      
      # Use the environment variables input below to pass secret variables to this script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cd nesasm/source && make && sudo make install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls && cd .. && ls'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'nesasm/nesasm w2.asm -s'